# Set to other image if needed
ARG BASE_IMAGE="vllm/vllm-openai:v0.17.0"

FROM ${BASE_IMAGE}

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

WORKDIR /workspace

RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir cmake

# Install unified-cache-management
COPY . /workspace/unified-cache-management

RUN pip config set global.index-url ${PIP_INDEX_URL}

RUN export PLATFORM="cuda" && \
    pip install -v -e /workspace/unified-cache-management --no-build-isolation

ENTRYPOINT ["/bin/bash"]